### ISSUE TITLE
Add flavor text for police encounters

### ISSUE THREAD

**Issue by snollygolly** [snollygolly/paw-wars#104]
Currently, when you're being chased by the police, you see the same text over and over.  It's boring and kind of confusing.  Some variety in this would be great.

**Comment by snollygolly** [comment]
Full should definitely be an array, maybe simple as well: https://github.com/snollygolly/paw-wars/blob/master/models/game/data/police.json

**Comment by snollygolly** [comment]
All of the police flavor text now resides in the localization module: https://github.com/snollygolly/paw-wars/tree/master/models/game/data/localization

This should make it significantly easier to add more.

**Comment by jiaming10** [comment]
Should this issue be closed, since the code already merged in?

**Comment by snollygolly** [comment]
Good catch, thanks!
