### ISSUE TITLE
Handle pluralization better

### ISSUE THREAD

**Issue by snollygolly** [snollygolly/paw-wars#16]
There are a number of spots in the code that don't handle any pluralization at all.  This should be fixed.

**Comment by snollygolly** [comment]
Example: https://github.com/snollygolly/paw-wars/blob/master/views/game_hotel.hbs#L6

The word "turns" doesn't change if you're only 1 turn old.

**Comment by METACEO** [comment]
I'm not too familiar with Handlebars... it doesn't look like it supports embedded conditional expressions. Maybe something like below?.. it's a little hack-ish, but incorrect pluralization can sure be distracting.

https://github.com/snollygolly/paw-wars/blob/master/views/game_hotel.hbs#L7
```html
...you're <strong>{{life.current.turn}}</strong> {{turn}} old and...
```
https://github.com/snollygolly/paw-wars/blob/master/controllers/game_hotel.js#L17
```javascript
yield this.render('game_hotel', {
	title: config.site.name,
	player: player,
	turn: (life.current.turn == 1) ? 'turn' : 'turns',
	life: life
});
```

**Comment by snollygolly** [comment]
@METACEO I appreciate the comment and the thoughts on how to handle pluralization!

I like your idea, but my concern is where there is multiple pluralization targets on the page, I'd need to handle those all in the controller before I render the view.  Your comment got me thinking it might be a good idea to write a `plural` handlebars helper.  You'd pass the singular version of the word, and the variable, and it would return either the singular or the plural version of the word.  That would prevent me from having to handle all that in the controller and pass that bit of logic to the view.

**Comment by METACEO** [comment]
I've usually determined the pluralization right there within the view (using Underscore's `template` method) but after looking more into Handlebars' `helper` approach, it looks it'll be just as you say.

**Comment by snollygolly** [comment]
My handlebars helper looks to work pretty good, so this issue is essentially closed.  I'll leave it open a bit longer for anyone to send a PR against in case I missed some pluralization targets (which I almost definitely did).

Usage of the helper is pretty easy: `{{plural 'turn' life.current.turn}}`

Where `'turn'` is the word you are potentially adding an "S" to, and the second parameter is the amount to look at.
