### ISSUE TITLE
Vendor Issue - 10 new health points not adding to current "health"

### ISSUE THREAD

**Issue by MonkeyWedge** [snollygolly/paw-wars#79]
When purchasing 10 new health points from the vendor it only increases the total capacity for health but it doesn't add 10 new health points. Screen shot attached:
![pawwars vendor health issue](https://cloud.githubusercontent.com/assets/13036552/13576025/33f1e1c2-e451-11e5-8d1d-670b4f04e60c.PNG)

**Comment by snollygolly** [comment]
Good find! I'll take a look at resolving this.

**Comment by snollygolly** [comment]
This should resolve the issue.  The expected behavior is for the health vendor to give you a +10hp boost in health points (current health) along with a +10hp boost in max health.  Both should update and display in the HUD.  Thanks for the issue!  Let me know if this doesn't behave as expected.
